server/src/main/java/Game/GamePiece.java
Initialized parent class for game pieces.
=> Adding GamePiece class.

server/src/main/java/Game/GameBoard.java, server/src/main/java/Game/GamePiece.java, server/src/main/java/Game/GiraffePiece.java
=> created board class

GameIP.md
Here is the initial version of GameIP.md. This document will specify the format for data that is to be exchanged between clients and the server. It will likely change significantly over the course of the project depending on teammate feedback and new developments. This document will be owned by the team and anyone may edit it so long as the team is in agreement. 
Closes #9
=> zachklau sprint1 Task 9 

ClientServerCommFormats.md, GameIP.md
Renamed GameIP to ClientServerCommFormat.
Consolidated communication types into four objects to be sent and recieved: Action, Update, ClientError, and ServerError
Renamed desiredPosition to desiredMoves and made it into a 2D array in case a piece moves more than one time in a turn.
Edited the description of userPassword to specify that it will be a hash of the password rather than the the password itself
From our discussions Thursday be talked about consolidating the objects into just a few rather than the many that there were initially. This updated consolidates them into Action, Update, ClientError, and ServerError. This is so that we don't have to create tons of different classes and duplicate code.
* Update 9/23: Removed ClientError object.*
Please comment any errors, mistakes, or …
=> Zachklau sprint1 task9

.idea/libraries/Maven__com_google_code_gson_gson_2_8_5.xml, server/README.md, server/pom.xml, server/src/main/java/webconnection/Action.java, server/src/main/java/webconnection/App.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/WebsocketServerTest.java
* Added Action class to model actions requested by clients. It contains data fields that the Action json object has.
* Added parseMessage() method to WebsocketServer which takes a message json from a client and uses gson to convert it to an Action object.
* Added junit tests for WebsocketServer and new Action class.
* Updated Server readme to include how to manually connect to web socket server and send data.
closes #50
=> Complete Task #50 - Use gson to parse client messages into Action objects

server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/WebsocketServerTest.java
* Added Update class for holding data of Update objects that will be sent to clients
* Renamed parseMessage to handleClientAction in WebsocketServer
* Added sendUpdateToClient to WebsocketServer for sending Update json objects to clients
* Added unit tests for Update to WebsocketServerTest
=> Complete Task 49 - Implement Update server class

server/pom.xml, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/DatabaseHandlerTest.java, server/src/test/java/WebsocketServerTest.java
DB tests are commented out until I can figure out a way to run them on Travis
=> Added Register, Unregister, & Login Functionality to DB

server/src/main/java/webconnection/UpdateFactory.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/UpdateFactoryTest.java
* UpdateFactory.java: Added UpdateFactory for coordinating server response to a client action. UpdateFactory takes an Action object and uses it to build an Update object by using the other server classes.
* WebsocketServer.java: Moved code from createUpdateMessage() and onMessage() to the corresponding methods in UpdateFactory. Made it so that onMessage creates an instance of UpdateFactory which will coordinate the server reponse to the client action.
* UpdateFactoryTest.java: Added JUnit tests for UpdateFactory methods.
Closes #83
=> Add UpdateFactory for coordinating server response to client actions

server/src/main/java/Game/ElephantPiece.java, server/src/main/java/Game/GamePiece.java, server/src/main/java/Game/GiraffePiece.java, server/src/main/java/Game/LionPiece.java, server/src/test/java/GiraffeTest.java
I provide refactoring for lion, giraffe and elephant. To implement move ( e.g. one step straight any direction) I used orthogonal/diagonal Move function to identify direction, then I checked the Manhattan Distance to check how many steps to move. Code is clean and error free!
=> Refactoring applied on Girrafe, Lion and Elephant

server/src/main/java/Game/CrocodilePiece.java, server/src/main/java/Game/ElephantPiece.java, server/src/main/java/Game/GameBoard.java, server/src/main/java/Game/GamePiece.java, server/src/main/java/Game/GiraffePiece.java, server/src/main/java/Game/LionPiece.java, server/src/main/java/Game/MonkeyPiece.java, server/src/main/java/Game/PawnPiece.java, server/src/main/java/Game/ZebraPiece.java, server/src/test/java/GiraffeTest.java
Major modifications have been provided : 
1. identify new function named validMoveLocation() in gameBoard and add it for every single piece. 
2. Some of the specific moves for pawn is moved from gamePiece to Pawn piece class. 
3. Some cleanup in lionPiece to get rid of number of returns.
=> Add validMoveLocation() function for every single piece. 

server/src/main/java/Game/GameBoard.java, server/src/main/java/Game/PawnPiece.java, server/src/test/java/PawnTest.java
1. Provide Major refactoring for Pawn Piece plus several new tests. Old long tests are passed and divided in  different functions to make them smaller. 
2. Delete print statement from gameBoard
=> Pawn Major Refactoring 

client/src/commObjects.js, client/src/components/Dashboard.js, client/src/components/Form.js, client/src/components/Game.js, client/src/components/Header.js, client/src/components/Home.js, client/src/components/styles/Form.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/DatabaseHandlerTest.java, server/src/test/java/ElephantTest.java, server/src/test/java/GiraffeTest.java, server/src/test/java/LionTest.java, server/src/test/java/PawnTest.java, server/src/test/java/UpdateFactoryTest.java, server/src/test/java/WebsocketServerTest.java
=> Rictor log out and UpdateFactory revisions

ClientServerCommFormats.md, server/src/main/java/webconnection/ServerError.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/ElephantTest.java, server/src/test/java/ServerErrorTest.java
* ClientServerCommFormats.md: Updated ServerError description and fields. Added error codes.
* ServerError.java: Added a class for communicating server errors to clients. Will be converted to JSONS. Errors are things like invalid password or invalid move.
* WebsocketServer.java: removed extra semicolon
* ElephantTest.java: removed unnecessary output
* ServerErrorTest.java: Added tests for ServerError.java
Closes #88
=> Add ServerError

ClientServerCommFormats.md, client/src/components/GameBoard.js, server/src/main/java/webconnection/Action.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/test/java/UpdateFactoryTest.java, server/src/test/java/WebsocketServerTest.java
User can select a move on the web page and entered "Confirm Move" to send the move request to server.  Server receives the request and calls performMove() to check and execute the move.  Server does not send back an error or updateBoard message yet.
requestMoves interface was implemented to have a string for pieceID  (e.g. pieceID = "M") and desiredMoves[] is now a 1D array of encoded integer values to specify the board locations.
=> Implemented a move request from client to server #95

README.md, client/package-lock.json, client/src/components/Game.js, client/src/components/Header.js, client/src/components/Invitations.js, server/src/main/java/database/DatabaseHandler.java
* Game.js: Added ability to select Invitations page
* Header.js: Made Header display Invitations page link if the user is logged in
* Invitations.js: Added Invitations.js to use as a page for users to see their invites and invite other users to a game
* DatabaseHandler.java: Made it so that the server is able to connect to the database through an ssh tunnel. This ability is activated via the environment variable TUNNEL.
* README.md: Added instructions for connecting to the database from off campus or when not on a cs lab machine
Closes #117
=> Zachklau add invitations client side and off campus database connection support

server/src/main/java/database/DatabaseHandler.java
=> Fixed variable name in DatabaseHander

ClientServerCommFormats.md, client/src/components/Game.js, client/src/components/Invitations.js, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/main/java/webconnection/WebsocketServer.java
Game.js: Added props to Invitation and added ability to process searchResult updates from the server
Invitation.js: Added search box and ability to search for other players on the server
ClientServerCommFormats.md: Aded searchUser and searchResult for searching the database for users
DatabaseHandler.java: added searchUser() for searching the database for a user
Query.java: Added createSearchUserQuery() for creating a query to search for a user
Update.java: Added the field userFound
UpdateFactory.java: Added buildSearchResult() for building a searchResult update
WebsockerServer.java: Removed serializeNulls() when converting objects to JSON to remove clutter from communication objects
=> Zachklau add user search for game invitation

server/src/main/java/game/GameBoard.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/test/java/PawnTest.java, server/src/test/java/UpdateFactoryTest.java
Game over Functionality:
- Before performing move, we check if opponent's lion in his castle, if so, we perform move ( obviously move needs to be legal in order to be able to capture the lion)
- After performing move, we again check the castle and check if he is still there, or he is gone! 
- If he is there, board get updated! players keep playing.  
- If lion is gone , that means that opponent's lion in captured!
- In this case game needs to be terminated! So, we send an update object toward client and tell him that Game is over.
- Winner is the current player that just captures the lion!
=> Please review carefully -- Fix GameOver functionality 

client/src/components/Game.js, client/src/components/GameBoard.js, client/src/components/styles/Form.scss, client/src/components/styles/Game.scss, client/src/components/styles/GameBoard.scss, client/src/components/styles/variables.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/game/Game.java, server/src/main/java/game/GameBoard.java, server/src/main/java/game/GamePiece.java, server/src/main/java/webconnection/ServerError.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/CrocodileTest.java, server/src/test/java/ElephantTest.java, server/src/test/java/GamePiecesTest.java, server/src/test/java/GiraffeTest.java, server/src/test/java/LionTest.java, server/src/test/java/MonkeyTest.java, server/src/test/java/PawnTest.java, server/src/test/java/ServerErrorTest.java, server/src/test/java/UpdateFactoryTest.java, server/src/test/java/WebsocketServerTest.java, server/src/test/java/ZebraTest.java
=> Rictor form error handling

client/src/components/Form.js, client/src/components/Game.js, client/src/components/Invitations.js, client/src/components/styles/Game.scss, client/src/components/styles/Invitations.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java
re #81 
search now provides list of users with ability to invite all
added submit on enter to search and Form (login, register)
=> Rictor search results

server/src/main/java/webconnection/UpdateFactory.java
there was tinny mistake, and that cause issue thrown an exception while capturing lion. it is fixed now.
=> fix winner when lion is captured

client/src/components/Game.js, client/src/components/GameBoard.js, client/src/components/styles/GameBoard.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/game/Game.java, server/src/main/java/game/GameBoard.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/test/java/DatabaseHandlerTest.java, server/src/test/java/GameTest.java, server/src/test/java/MonkeyTest.java, server/src/test/java/UpdateFactoryTest.java
Also added indicators on the web page to show whose turn it is.  They are not styled perfectly, but this is a first pass solution.
=> Fix turn sequencing.  Convert to using the database for all moves.  

server/src/main/java/webconnection/UpdateFactory.java
for endCondition I am sending 
- "won" for when a player wins the game and game terminates.
-  null (for now) if game is still going on and no winner is specifying yet. 
another endCondition needs to be handled later named "quit", when a player quits a game.
=> Handle win situation, specify winner and send a proper update back to client. 

ClientServerCommFormats.md, README.md, client/src/components/Game.js, client/src/components/GameBoard.js, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/game/Game.java, server/src/main/java/webconnection/UpdateFactory.java
Updated the pull to make sure we are disabling all the squares on the board as well as the move buttons after someone has won the game.
=> Mln sp3 1122

client/src/components/Form.js
=> Rictor user validation

ClientServerCommFormats.md, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/test/java/DatabaseHandlerTest.java, server/src/test/java/UpdateFactoryTest.java
I know that the end time for the update is still not working. I will be making this a separate issue
=> Server Implementation of Abandon Game

ClientServerCommFormats.md, client/src/components/Game.js, client/src/components/Invitations.js, client/src/components/styles/Invitations.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java
Added the ability for users to see their invitations on the invitations page. See commit history for details.
closes #133
=> Add Invitations Display

ClientServerCommFormats.md, client/src/components/Game.js, client/src/components/GameBoard.js, client/src/components/Header.js, client/src/components/MyGames.js, client/src/components/styles/MyGames.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/UpdateFactory.java
Added a new page which is accessible from the Home page (MyGames) to view all your active games.
You can select a game, but it doesn't set that up totally correctly yet.
Displays all your active games when you load the page.
You can filter to get just certain opponents.
Styling can still be improved. This is first pass to get some functionality in place.
After loading the game board page, client now sends a request for game status info to load the board.
=> Added page to view active games #154 & #60

ClientServerCommFormats.md, client/src/components/Game.js, client/src/components/Invitations.js, client/src/components/styles/Invitations.scss, server/pom.xml, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/UpdateFactory.java
Added the functionality for a user to reject an invitation from another user. See commit history for more details on what was changed/added.
closes #178
=> Added reject invitation functionality

README.md, client/src/components/GameBoard.js, client/src/components/styles/GameBoard.scss, client/src/components/styles/variables.scss, server/src/main/java/game/GameBoard.java, server/src/main/java/game/PawnPiece.java, server/src/test/java/PawnTest.java, server/src/test/java/UpdateFactoryTest.java
- Change super pawn icon to able able to distinguish a pawn from super pawn 
- Change board's colors
=> Fari - fix super pawn icon 

server/src/main/java/database/DatabaseHandler.java
Just making the same changes to the code that went in between the last time I pulled master for the branch that merged last night.
For all future changes to DatabaseHandler, you should not be creating a new connection. Instead, use the class `con` variable.
=> removed new connections created/passed in DatabaseHandler

client/src/components/Dashboard.js, client/src/components/MyGames.js, client/src/components/styles/Dashboard.scss, client/src/components/styles/Invitations.scss, client/src/components/styles/MyGames.scss, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/Action.java, server/src/main/java/webconnection/UpdateFactory.java
Added status filters to game search, allowing user to search any current or previous game with option to filter on status
Also changed results to display game status
=> Rictor game filters

client/src/components/Game.js, client/src/components/GameBoard.js, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/webconnection/WebsocketServer.java
sent a copy of the state instead of the actual state which gets cleared immediately after/during sending it into an asynchronous process to send it
also got rid of extraneous print statements in a few places
=> whoops sorry guys

ClientServerCommFormats.md, client/src/components/Game.js, client/src/components/Invitations.js, server/src/main/java/game/Game.java, server/src/main/java/webconnection/UpdateFactory.java
Make it so that when a user accepts an invitation, a new game is created between them and the one who invited them and remove the invitation.
closes #183
=> Add invitation acceptance functionality

server/src/main/java/database/Query.java
I created new columns in the database called `startTime` and `endTime`. when this PR is merged, I will delete the columns `start` and `end`
=> Fix start and stop times in db

client/src/components/Invitations.js
=> Fix bug with "No sent invitations to show" not displaying

client/src/components/Dashboard.js, client/src/components/Game.js, client/src/components/GameBoard.js, client/src/components/Header.js, client/src/components/Home.js, client/src/components/Invitations.js, client/src/components/MyGames.js, client/src/components/styles/GameBoard.scss, server/src/main/java/game/Game.java, server/src/main/java/webconnection/Update.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/main/java/webconnection/WebsocketServer.java, server/src/test/java/GameTest.java, server/src/test/java/UpdateFactoryTest.java
Server now updates all players in a game after either makes a move
Server now validates that requesting user is owner of moved piece
Server now validates that requesting user is player in game
Client shows colored circles around logged in player's pieces
Client shows "Loading..." instead of default board
Also did some cleaning so our client console is less messy with warnings and log statements
=> Rictor distinguish player pieces and live updates!

client/src/components/GameBoard.js, client/src/components/styles/GameBoard.scss
flips pieces to face player (when not already facing player)
=> Rictor flip board

client/src/components/Game.js, client/src/components/Invitations.js, client/src/components/Profile.js, client/src/components/styles/Game.scss, client/src/components/styles/Invitations.scss, client/src/components/styles/MyGames.scss
threw this together in a couple of hours, so take a close look or feel free to add more info
=> super basic profile page, only shows game history

server/src/main/java/database/DatabaseHandler.java
probably not a big deal but just another small dent in our connection overhead
=> close even more connections, this time with statements & result sets

ClientServerCommFormats.md, client/src/components/Game.js, client/src/components/GameBoard.js, client/src/components/MyGames.js, client/src/components/Profile.js, server/src/main/java/database/Query.java, server/src/main/java/webconnection/UpdateFactory.java
Team - please take a look at this code and see if you like or dislike the changes.  I'm willing to revert back on the changes made to the game filters and displays.
Changes - 
* Enabled us to load all games - abandoned, completed(won) or in progress.  We were missing the first 2 cases.
* changed the behavior of the game status filters.  
* Now we react immediately on changing the pull down menu (in progress, finished, abandoned, all)
=> Load a completed or abandonded game.  Also changed filtering on game search

client/src/components/MyGames.js
Made so that games open in a pop-up window rather than a new tab. Fixed it so that multiple pop up windows for multiple games can be open at once
closes #221
=> Pop up windows and multiple open games fix

server/pom.xml, server/src/main/java/database/DatabaseHandler.java, server/src/main/java/database/Query.java, server/src/main/java/webconnection/UpdateFactory.java, server/src/test/java/DatabaseHandlerTest.java
- sends email when rejected/accepted
- small fix so that the user who invited a person gets to go first
=> Send email notifications

client/src/components/Dashboard.js, client/src/components/Game.js, client/src/components/Home.js, client/src/components/MyGames.js
Makes it so that when a user accepts an invitation, their games list is refreshed so that the newly created game appears.
closes #201
=> Refresh the user's games list upon acceptance of an inviation
